[package]
name = "keyboard_driver"
version = "0.1.0"
edition = "2021"

[lib]
name = "keyboard_driver"
crate-type = ["staticlib"]

[[bin]]
name = "keyboard_driver"
path = "src/main.rs"

[dependencies]

