[package]
name = "ahci-driver"
version = "0.1.0"
edition = "2021"

[lib]
name = "ahci_driver"
path = "src/lib.rs"

[[bin]]
name = "ahci"
path = "src/main.rs"

[dependencies]
driver-framework = { path = "../../framework" }
